*** Assumptions:
*** 1. A link is one to one.
*** 2. Both ingress and egress of a link have the same cap.
*** 3. A reservation has only honest ASes on its path.

load parameters
load initial-state
---load path-table 

mod ANALYSIS is
  inc PARAMETERS + NAMES + PATH-GENERATOR .

  op initConfig : -> Config .
  eq initConfig = run(initState,LIMIT) .
  
  --- #sources, #intermediates, #destinations
  eq initState = init(10,480,10) .
  
  
  var C : Config .  var O : Address .
  var RS : Map{ReservationId,Snapshots} .  var SS : Snapshots .
  var RID : ReservationId .  vars T FL CAP : Float .
  vars REST REST' : AttributeSet .
	
  --- "local" analysis w/o SMC
  
  *** the last snapshot for each reservation
  op snapshots : Config -> Map{ReservationId,Snapshots} .
  op snapshots : Map{ReservationId,Snapshots} Config -> Map{ReservationId,Snapshots} .
  eq snapshots(< O : Monitor | snapshots: RS > C) = snapshots(RS,C) .
  eq snapshots((RID |-> (SS ;; < T FL O >), RS),(C < O : Node | sink: CAP, REST >)) 
   = ((RID |-> < T FL O CAP >), snapshots(RS,(C < O : Node | sink: CAP, REST >))) .
  eq snapshots(empty,C) = empty .
  	
	
	
	
	*** New Scenarios
    --- common parameters
    --- delta = 0.8
    --- capacity: A 100 B 200 C 125 D 150
	
	---(
    --- Scenario 1, Fig.2
    --- demands: 20, 80, 60
    --- allocated: 15, 60, 45
    ---
    eq initState = { 0.0 | nil } 
       < m : Monitor | snapshots: empty > [5.0, snapshot to m, 0]
	 
       < tb : Table | paths: ((n1 ; n4) ;; (n2 ; n4) ;; (n3 ; n4)),
	                  links: (< n1 n4 1 (100.0 * delta) > ;; < n2 n4 1 (200.0 * delta) > 
					          ;; < n3 n4 1 (125.0 * delta) >) >
							
       < n1 : Node | reservationMap: empty,
                     sqn: 0, sink: 0.0  > 
       < n2 : Node | reservationMap: empty,
                     sqn: 0, sink: 0.0 >
       < n3 : Node | reservationMap: empty,
                     sqn: 0, sink: 0.0 >
       < n4 : Node | reservationMap: empty,
                     sqn: 0, sink: (150.0 * delta) >

      [0.0, crtr((n1 ; n4),n4,minBW,20.0,maxT,n1), 0]
      [2.0, crtr((n2 ; n4),n4,minBW,80.0,maxT,n2), 0]
      [1.0, crtr((n3 ; n4),n4,minBW,60.0,maxT,n3), 0]
  				   .
  	)
	
  --- Scenario 2, Fig.3
  --- demands: 20, 400 (200 + 200), 60
  --- allocated: 10, 80, 30
  --- a1 and a2 are attackers, both requesting from the same ingress to egress
  ---(
  eq initState = { 0.0 | nil }
     < m : Monitor | snapshots: empty > [5.0, snapshot to m, 0]
     < tb : Table | paths: ((n1 ; n4) ;; (a1 ; n2 ; n4) ;; 
	                        (a2 ; n2 ; n4) ;; (n3 ; n4)),
					links: (< n1 n4 1 (100.0 * delta) > ;; < n2 n4 1 (200.0 * delta) > 
					          ;; < n3 n4 1 (125.0 * delta) > 
							  ;; < a1 n2 1 Infinity > ;; < a2 n2 1 Infinity >) > 
							
     < n1 : Node | reservationMap: empty,
                   sqn: 0, sink: 0.0  > 
     < n2 : Node | reservationMap: empty,
                   sqn: 0, sink: 0.0  >
     < n3 : Node | reservationMap: empty,
                   sqn: 0, sink: 0.0 >
     < n4 : Node | reservationMap: empty,
                   sqn: 0, sink: (150.0 * delta) >			   
     < a1 : Node | reservationMap: empty,
                   sqn: 0, sink: 0.0  > 
     < a2 : Node | reservationMap: empty,
                   sqn: 0, sink: 0.0  >

    [0.0, crtr((n1 ; n4),n4,minBW,20.0,maxT,n1), 0]
    [0.0, crtr((a1 ; n2 ; n4),(n2 ; n4),minBW,200.0,maxT,a1), 0]
	[0.0, crtr((a2 ; n2 ; n4),(n2 ; n4),minBW,200.0,maxT,a2), 0]
    [0.0, crtr((n3 ; n4),n4,minBW,60.0,maxT,n3), 0]
				   .
	)
	
    --- Scenario 3, Fig.4
    --- demands: 80 (a1), 120 (a1), 60
    --- allocated: 32, 48, 40
    ---(
    eq initState = { 0.0 | nil }
       < m : Monitor | snapshots: empty > [5.0, snapshot to m, 0]
       < tb : Table | paths: ((a1 ; n1 ; n4) ;; (a1 ; n4) ;; (n3 ; n4)),
	                  links: (< n1 n4 1 (100.0 * delta) > ;; < a1 n4 1 (200.0 * delta) > 
					          ;; < n3 n4 1 (125.0 * delta) > ;; < a1 n1 1 Infinity >) > 
							
       < a1 : Node | reservationMap: empty,
                     sqn: 0, sink: 0.0  > 
       < n1 : Node | reservationMap: empty,
                     sqn: 0, sink: 0.0 >
       < n3 : Node | reservationMap: empty,
                     sqn: 0, sink: 0.0 >
       < n4 : Node | reservationMap: empty,
                     sqn: 0, sink: (150.0 * delta) >	

      [2.0, crtr((a1 ; n1 ; n4),(n1 ; n4),minBW,80.0,maxT,a1), 0]
      [1.0, crtr((a1 ; n4),n4,minBW,120.0,maxT,a1), 0]
      [3.0, crtr((n3 ; n4),n4,minBW,60.0,maxT,n3), 0]
  				   .
  	)
	
  --- Scenario 4, Fig.5
  --- demands: 80 (a3), 160 (a1,a2), 60
  --- allocated: 32, 64, 24
  ---(
  eq initState = { 0.0 | nil }
     < m : Monitor | snapshots: empty > [sampleExp(1.0), snapshot to m, 0]
     < tb : Table | paths: ((a3 ; n4) ;; (a1 ; n2 ; n4) ;; (a2 ; n2 ; n4) ;; (n3 ; n4)),
	                links: (< a3 n4 1 (100.0 * delta) > ;; < n2 n4 1 (200.0 * delta) > 
					        ;; < a1 n2 1 Infinity > ;; < a2 n2 1 Infinity >
							;; < n3 n4 1 (125.0 * delta) >) > 
							
     < a3 : Node | reservationMap: empty,
                   sqn: 0, sink: 0.0  > 
				   
     < n2 : Node | reservationMap: empty,
                   sqn: 0, sink: 0.0  >
     < n3 : Node | reservationMap: empty,
                   sqn: 0, sink: 0.0 >
     < n4 : Node | reservationMap: empty,
                   sqn: 0, sink: (150.0 * delta) >
				   
     < a1 : Node | reservationMap: empty,
                   sqn: 0, sink: 0.0  > 
     < a2 : Node | reservationMap: empty,
                   sqn: 0, sink: 0.0  >

    [1.0, crtr((a3 ; n4),n4,minBW,80.0,maxT,a3), 0]
    [3.0, crtr((a1 ; n2 ; n4),(n2 ; n4),minBW,80.0,maxT,a1), 0]
	[2.0, crtr((a2 ; n2 ; n4),(n2 ; n4),minBW,80.0,maxT,a2), 0]
    [0.0, crtr((n3 ; n4),n4,minBW,60.0,maxT,n3), 0]
				   .  
  )
endm

set clear rules off .
---rew initConfig .
rew snapshots(initConfig) .

q